name: Labeler
on:
  pull_request:
    branches: ["main"]
jobs:
  assign-labels:
    name: Assign labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: zattoo/labaler@v2
        with:
          token: ${{github.token}}
          source: ".labels"
