name: automerge
on:
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
jobs:
  automerge:
    if: (github.event.review.state == 'approved' && github.ref_protected == false)
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}
      - uses: actions/checkout@v3
      - uses: devmasx/merge-branch@master
        name: Merging the PR from dev to master...
        with:
          type: now
          from_branch: dev
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
