name: automerge_am
on:
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - run: echo "PR merged automatically! hehehe"
      - run: echo "Starting automatic merge... dev to main"
      - run: |
          git checkout origin
          git merge dev -m "Merging dev to main" --no-ff
      - run: echo "Merge completed!"
