name: dump_env
on:
  workflow_dispatch:
jobs:
  env:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Dump GitHub context
        id: github_context_step
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}
